fix(templates): example

diff --git a/.github/workflows/build-examples.yml b/.github/workflows/build-examples.yml
--- a/.github/workflows/build-examples.yml
+++ b/.github/workflows/build-examples.yml
@@ -44,38 +44,17 @@ jobs:
           INTEGRATION: ${{ matrix.integration }}
         run: |
           mkdir -p $WEBHOOK_DIR
-          cp -r utils/. $WEBHOOK_DIR && cp -r utils/* $WEBHOOK_DIR
+          cp -r templates/example $WEBHOOK_DIR && cp -r templates/example/* $WEBHOOK_DIR
           mv $WEBHOOK_DIR/package.example.json $WEBHOOK_DIR/package.json
-          cd utils/scripts && yarn && cd ../../ && \
-            npx ts-node ./utils/scripts/index.ts && \
-            npx ts-node ./utils/scripts/js/writeGithubAction.ts
+          cd templates/scripts && yarn && cd ../../ && \
+            npx ts-node ./templates/scripts/generate.ts && \
+            npx ts-node ./templates/scripts/steps/github-action.ts
           sed -i "s/\@indent\/integration-example/\@indent\/integration-${INTEGRATION}/g" $WEBHOOK_DIR/package.json
-          rm -r $WEBHOOK_DIR/scripts/*.ts && rm -r $WEBHOOK_DIR/scripts/js
 
       - name: Setup SSH
         uses: webfactory/ssh-agent@ee29fafb6aa450493bac9136b346e51ea60a8b5e
         with:
           ssh-private-key: ${{ secrets.INDENT_BOT_SSH_PRIVATE_KEY }}
-
-      - name: Synchronize ${{ matrix.integration }} using Copybara
-        env:
-          GH_TOKEN: ${{ secrets.IndentBotKey }}
-          WORKFLOW: ${{ matrix.integration }}
-        run: |
-          git config --global user.name "Indent Bot"
-          git config --global user.email "indent-bot@indent.com"
-          echo "https://indent-bot:${GH_TOKEN}@api.github.com" > ~/.git-credentials
-          echo "Running Copybara..."
-          GITHUB_REF=. make copybara-${WORKFLOW} COPYBARA_FLAGS="--github-destination-pr-branch copybara-integration-sync $([[ $GITHUB_REF == *"pull"* ]] && echo "--dry-run")" 2>&1 | tee /tmp/copybara-logs
-          if [[ -n $(</tmp/copybara-logs grep "make: ***" | grep "Error") ]]; then
-                  if [[ -n $(</tmp/copybara-logs grep "Migration of the revision resulted in an empty change") ]]; then
-                          echo "Already up-to-date, skipping..."
-                          exit 0
-                  fi
-                  echo "Encountered error"
-                  exit 2
-          fi
-          echo "Copybara ran successfully"
 
       - name: Build example (${{ matrix.integration }})
         env:
@@ -105,3 +84,23 @@ jobs:
           aws s3 cp ./dist/function.zip \
             s3://${{ env.ARTIFACT_S3_BUCKET }}/webhooks/aws/lambda/${{ matrix.integration }}-${{ env.INDENT_TAG }}-function.zip \
             --acl public-read
+
+      - name: Sync ${{ matrix.integration }} using Copybara
+        env:
+          GH_TOKEN: ${{ secrets.IndentBotKey }}
+          WORKFLOW: ${{ matrix.integration }}
+        run: |
+          git config --global user.name "Indent Bot"
+          git config --global user.email "indent-bot@indent.com"
+          echo "https://indent-bot:${GH_TOKEN}@api.github.com" > ~/.git-credentials
+          echo "Running Copybara..."
+          GITHUB_REF=. make copybara-${WORKFLOW} COPYBARA_FLAGS="--github-destination-pr-branch copybara-integration-sync $([[ $GITHUB_REF == *"pull"* ]] && echo "--dry-run")" 2>&1 | tee /tmp/copybara-logs
+          if [[ -n $(</tmp/copybara-logs grep "make: ***" | grep "Error") ]]; then
+                  if [[ -n $(</tmp/copybara-logs grep "Migration of the revision resulted in an empty change") ]]; then
+                          echo "Already up-to-date, skipping..."
+                          exit 0
+                  fi
+                  echo "Encountered error"
+                  exit 2
+          fi
+          echo "Copybara ran successfully"
